In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("D:\PROJECT\medical\KaggleV2-May-2016.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64
 2   Gender          110527 non-null  object
 3   ScheduledDay    110527 non-null  object
 4   AppointmentDay  110527 non-null  object
 5   Age             110527 non-null  int64
 6   Neighbourhood   110527 non-null  object
 7   Scholarship     110527 non-null  int64
 8   Hipertension    110527 non-null  int64
 9   Diabetes        110527 non-null  int64
 10  Alcoholism      110527 non-null  int64
 11  Handcap         110527 non-null  int64
 12  SMS_received    110527 non-null  int64
 13  No-show         110527 non-null  object
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB

In [4]:
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [5]:
df.ScheduledDay= pd.to_datetime(df.ScheduledDay)
df.AppointmentDay = pd.to_datetime(df.AppointmentDay)

df['Scheduled_Date'] = df.ScheduledDay.dt.date
df['Schedule_Hour'] = df.ScheduledDay.dt.hour
df['Schedule_Weekday'] = df.ScheduledDay.dt.day_name()

df['Appointment_Date'] = df.AppointmentDay.dt.date
df['Appointment_Weekday'] = df.AppointmentDay.dt.day_name()

df["Waiting_days"] = (
    df["AppointmentDay"].dt.normalize()
    - df["ScheduledDay"].dt.normalize()
).dt.days

In [6]:
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show,Scheduled_Date,Schedule_Hour,Schedule_Weekday,Appointment_Date,Appointment_Weekday,Waiting_days
0,2.987250e+13,5642903,F,2016-04-29 18:38:08+00:00,2016-04-29 00:00:00+00:00,62,JARDIM DA PENHA,0,1,0,0,0,0,No,2016-04-29,18,Friday,2016-04-29,Friday,0
1,5.589978e+14,5642503,M,2016-04-29 16:08:27+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,0,0,0,0,0,No,2016-04-29,16,Friday,2016-04-29,Friday,0
2,4.262962e+12,5642549,F,2016-04-29 16:19:04+00:00,2016-04-29 00:00:00+00:00,62,MATA DA PRAIA,0,0,0,0,0,0,No,2016-04-29,16,Friday,2016-04-29,Friday,0
3,8.679512e+11,5642828,F,2016-04-29 17:29:31+00:00,2016-04-29 00:00:00+00:00,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No,2016-04-29,17,Friday,2016-04-29,Friday,0
4,8.841186e+12,5642494,F,2016-04-29 16:07:23+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,1,1,0,0,0,No,2016-04-29,16,Friday,2016-04-29,Friday,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 20 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   PatientId            110527 non-null  float64
 1   AppointmentID        110527 non-null  int64
 2   Gender               110527 non-null  object
 3   ScheduledDay         110527 non-null  datetime64[ns, UTC]
 4   AppointmentDay       110527 non-null  datetime64[ns, UTC]
 5   Age                  110527 non-null  int64
 6   Neighbourhood        110527 non-null  object
 7   Scholarship          110527 non-null  int64
 8   Hipertension         110527 non-null  int64
 9   Diabetes             110527 non-null  int64
 10  Alcoholism           110527 non-null  int64
 11  Handcap              110527 non-null  int64
 12  SMS_received         110527 non-null  int64
 13  No-show              110527 non-null  object
 14  Scheduled_Date       110527 non-null  object
 15  Schedule_Hour        110527 non-null  int32
 16  Schedule_Weekday     110527 non-null  object
 17  Appointment_Date     110527 non-null  object
 18  Appointment_Weekday  110527 non-null  object
 19  Waiting_days         110527 non-null  int64
dtypes: datetime64[ns, UTC](2), float64(1), int32(1), int64(9), object(7)
memory usage: 16.4+ MB

In [8]:
df['Appointment_Date'] = pd.to_datetime(df['Appointment_Date'])
df['Scheduled_Date'] =pd.to_datetime(df['Scheduled_Date'])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 20 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   PatientId            110527 non-null  float64
 1   AppointmentID        110527 non-null  int64
 2   Gender               110527 non-null  object
 3   ScheduledDay         110527 non-null  datetime64[ns, UTC]
 4   AppointmentDay       110527 non-null  datetime64[ns, UTC]
 5   Age                  110527 non-null  int64
 6   Neighbourhood        110527 non-null  object
 7   Scholarship          110527 non-null  int64
 8   Hipertension         110527 non-null  int64
 9   Diabetes             110527 non-null  int64
 10  Alcoholism           110527 non-null  int64
 11  Handcap              110527 non-null  int64
 12  SMS_received         110527 non-null  int64
 13  No-show              110527 non-null  object
 14  Scheduled_Date       110527 non-null  datetime64[ns]
 15  Schedule_Hour        110527 non-null  int32
 16  Schedule_Weekday     110527 non-null  object
 17  Appointment_Date     110527 non-null  datetime64[ns]
 18  Appointment_Weekday  110527 non-null  object
 19  Waiting_days         110527 non-null  int64
dtypes: datetime64[ns, UTC](2), datetime64[ns](2), float64(1), int32(1), int64(9), object(5)
memory usage: 16.4+ MB

In [10]:
df["PatientId"].dtype

dtype('float64')

In [11]:
df['PatientId'] = df['PatientId'].astype('string')

In [12]:
df['PatientId'].isnull().sum()

np.int64(0)

In [13]:
df['PatientId'].isnull().sum()

np.int64(0)

In [14]:
df['AppointmentID'].duplicated().sum()

np.int64(0)

In [15]:
labels = ['Young Adult', 'Adult', 'Middle-Aged', 'Senior']
df['Age_Group'] = pd.qcut(df.Age, q = 4, labels = labels)

In [16]:
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,...,Handcap,SMS_received,No-show,Scheduled_Date,Schedule_Hour,Schedule_Weekday,Appointment_Date,Appointment_Weekday,Waiting_days,Age_Group
0,29872499824296.0,5642903,F,2016-04-29 18:38:08+00:00,2016-04-29 00:00:00+00:00,62,JARDIM DA PENHA,0,1,0,...,0,0,No,2016-04-29,18,Friday,2016-04-29,Friday,0,Senior
1,558997776694438.0,5642503,M,2016-04-29 16:08:27+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,0,0,...,0,0,No,2016-04-29,16,Friday,2016-04-29,Friday,0,Senior
2,4262962299951.0,5642549,F,2016-04-29 16:19:04+00:00,2016-04-29 00:00:00+00:00,62,MATA DA PRAIA,0,0,0,...,0,0,No,2016-04-29,16,Friday,2016-04-29,Friday,0,Senior
3,867951213174.0,5642828,F,2016-04-29 17:29:31+00:00,2016-04-29 00:00:00+00:00,8,PONTAL DE CAMBURI,0,0,0,...,0,0,No,2016-04-29,17,Friday,2016-04-29,Friday,0,Young Adult
4,8841186448183.0,5642494,F,2016-04-29 16:07:23+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,1,1,...,0,0,No,2016-04-29,16,Friday,2016-04-29,Friday,0,Senior

In [17]:
def show_up(show):
    if show == 'No':
        return 1
    else:
        return 0
df['Show_up'] = df['No-show'].apply(show_up)

In [18]:
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,...,SMS_received,No-show,Scheduled_Date,Schedule_Hour,Schedule_Weekday,Appointment_Date,Appointment_Weekday,Waiting_days,Age_Group,Show_up
0,29872499824296.0,5642903,F,2016-04-29 18:38:08+00:00,2016-04-29 00:00:00+00:00,62,JARDIM DA PENHA,0,1,0,...,0,No,2016-04-29,18,Friday,2016-04-29,Friday,0,Senior,1
1,558997776694438.0,5642503,M,2016-04-29 16:08:27+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,0,0,...,0,No,2016-04-29,16,Friday,2016-04-29,Friday,0,Senior,1
2,4262962299951.0,5642549,F,2016-04-29 16:19:04+00:00,2016-04-29 00:00:00+00:00,62,MATA DA PRAIA,0,0,0,...,0,No,2016-04-29,16,Friday,2016-04-29,Friday,0,Senior,1
3,867951213174.0,5642828,F,2016-04-29 17:29:31+00:00,2016-04-29 00:00:00+00:00,8,PONTAL DE CAMBURI,0,0,0,...,0,No,2016-04-29,17,Friday,2016-04-29,Friday,0,Young Adult,1
4,8841186448183.0,5642494,F,2016-04-29 16:07:23+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,1,1,...,0,No,2016-04-29,16,Friday,2016-04-29,Friday,0,Senior,1

In [19]:
def age_group(age):
    if age < 18:
        return 'Under 18'
    elif age < 30:
        return 'Young Adult'
    elif age < 45:
        return 'Adult'
    elif age < 60:
        return 'Middle-Aged'
    else:
        return 'Senior'

df['Age_Group'] = df['Age'].apply(age_group)

In [20]:
df = df.drop(['ScheduledDay', 'AppointmentDay', 'No-show'], axis = 1)

In [21]:
def waiting_group(day):
    if day >= 0 and day <= 3:
        return '0-3 days'
    if day >= 4 and day <= 7:
        return '4-7 days'
    if day >= 8 and day <= 14:
        return '8-14 days'
    if day >= 15 and day <= 30:
        return '15-30 days'
    else:
        return '31+ days'
df['Waiting_group'] = df['Waiting_days'].apply(waiting_group)

In [22]:
df['Conditions'] = df['Hipertension'] + df['Diabetes'] + df['Alcoholism'] + df['Handcap']

In [23]:
df.head()

,PatientId,AppointmentID,Gender,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,...,Scheduled_Date,Schedule_Hour,Schedule_Weekday,Appointment_Date,Appointment_Weekday,Waiting_days,Age_Group,Show_up,Waiting_group,Conditions
0,29872499824296.0,5642903,F,62,JARDIM DA PENHA,0,1,0,0,0,...,2016-04-29,18,Friday,2016-04-29,Friday,0,Senior,1,0-3 days,1
1,558997776694438.0,5642503,M,56,JARDIM DA PENHA,0,0,0,0,0,...,2016-04-29,16,Friday,2016-04-29,Friday,0,Middle-Aged,1,0-3 days,0
2,4262962299951.0,5642549,F,62,MATA DA PRAIA,0,0,0,0,0,...,2016-04-29,16,Friday,2016-04-29,Friday,0,Senior,1,0-3 days,0
3,867951213174.0,5642828,F,8,PONTAL DE CAMBURI,0,0,0,0,0,...,2016-04-29,17,Friday,2016-04-29,Friday,0,Under 18,1,0-3 days,0
4,8841186448183.0,5642494,F,56,JARDIM DA PENHA,0,1,1,0,0,...,2016-04-29,16,Friday,2016-04-29,Friday,0,Middle-Aged,1,0-3 days,2

In [24]:
df.to_csv('Healthcare Marketing Analytics.csv', index=False, encoding='utf-8-sig')
from google.colab import files
files.download('Healthcare Marketing Analytics.csv')

ModuleNotFoundError: No module named 'google.colab'